services:
  postgres:
    container_name: cse115a-timelogger-backend
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      # - ./sql/indexes.sql:/docker-entrypoint-initdb.d/4.indexes.sql
